
- hosts: all
  become: yes
  become_user: root
  tasks:
     - name: Install Docker Engine
       apt:
        name: docker.io
        state: present
     - name: Install Docker CLI
       apt:
        name: docker-compose
        state: present

     - name : Start docker service
       service:
           name: "docker"
           state: started
           enabled: yes

    # - name: installing Python library for docker
    #   command: "pip3 install docker"

     - name: Creating webpage folder
       file:
            path: /webpages
            state: directory
     - name: Copying html file used for webserver
       copy:
            src: "app.html"
            dest: "/webpages/"

     - name: Creating container using httpd Image
       docker_container:
            name: Mywebserver
            image: httpd
            state: started
            exposed_ports: "80"
            ports: "1999:80"
            volumes:
            -  /webpages:/usr/local/apache2/htdocs/
            
